"""
Seed script: populates the `products` collection in MongoDB with sample pharmacy products.
Run from the backend directory:
    python scripts/seed_products.py
"""

import asyncio
import os
import sys
from datetime import datetime
from pathlib import Path

# Allow imports from the backend root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv
load_dotenv()

from motor.motor_asyncio import AsyncIOMotorClient
from pymongo.server_api import ServerApi

PRODUCTS = [
    # ── Diabetes Care ──────────────────────────────────────────────────────────
    {
        "name": "Metformin 500mg Tablets",
        "category": "medicines",
        "health_concern": "diabetes",
        "price": 45.0,
        "original_price": 60.0,
        "stock": 200,
        "description": "Oral antidiabetic medication for type 2 diabetes management.",
        "manufacturer": "Sun Pharma",
        "requires_prescription": True,
        "dosage_form": "tablet",
        "strength": "500mg",
        "pack_size": "30 tablets",
        "rating": 4.5,
        "reviews_count": 312,
        "in_stock": True,
    },
    {
        "name": "Glucometer OneTouch Select Plus",
        "category": "medical_devices",
        "health_concern": "diabetes",
        "price": 1299.0,
        "original_price": 1799.0,
        "stock": 50,
        "description": "Easy-to-use blood glucose monitoring system with large display.",
        "manufacturer": "LifeScan",
        "requires_prescription": False,
        "dosage_form": None,
        "strength": None,
        "pack_size": "1 device + 10 strips",
        "rating": 4.7,
        "reviews_count": 890,
        "in_stock": True,
    },
    {
        "name": "Glucon-D Instant Energy Drink",
        "category": "diet_nutrition",
        "health_concern": "diabetes",
        "price": 99.0,
        "original_price": 120.0,
        "stock": 150,
        "description": "Glucose-based energy drink for quick energy replenishment.",
        "manufacturer": "Heinz",
        "requires_prescription": False,
        "dosage_form": "powder",
        "strength": None,
        "pack_size": "500g",
        "rating": 4.2,
        "reviews_count": 540,
        "in_stock": True,
    },
    {
        "name": "Diabetic Care Foot Cream",
        "category": "personal_care",
        "health_concern": "diabetes",
        "price": 249.0,
        "original_price": 299.0,
        "stock": 80,
        "description": "Specially formulated moisturising cream for diabetic foot care.",
        "manufacturer": "Himalaya",
        "requires_prescription": False,
        "dosage_form": "cream",
        "strength": None,
        "pack_size": "100g",
        "rating": 4.3,
        "reviews_count": 210,
        "in_stock": True,
    },

    # ── Heart Health ───────────────────────────────────────────────────────────
    {
        "name": "Atorvastatin 10mg Tablets",
        "category": "medicines",
        "health_concern": "heart",
        "price": 85.0,
        "original_price": 110.0,
        "stock": 180,
        "description": "Statin medication to lower LDL cholesterol and reduce cardiovascular risk.",
        "manufacturer": "Cipla",
        "requires_prescription": True,
        "dosage_form": "tablet",
        "strength": "10mg",
        "pack_size": "30 tablets",
        "rating": 4.6,
        "reviews_count": 425,
        "in_stock": True,
    },
    {
        "name": "Omega-3 Fish Oil 1000mg",
        "category": "vitamins",
        "health_concern": "heart",
        "price": 399.0,
        "original_price": 499.0,
        "stock": 120,
        "description": "High-potency omega-3 fatty acids for heart and brain health.",
        "manufacturer": "HealthKart",
        "requires_prescription": False,
        "dosage_form": "softgel",
        "strength": "1000mg",
        "pack_size": "60 softgels",
        "rating": 4.5,
        "reviews_count": 1230,
        "in_stock": True,
    },
    {
        "name": "Digital Blood Pressure Monitor",
        "category": "medical_devices",
        "health_concern": "heart",
        "price": 1599.0,
        "original_price": 2199.0,
        "stock": 40,
        "description": "Automatic upper arm BP monitor with irregular heartbeat detection.",
        "manufacturer": "Omron",
        "requires_prescription": False,
        "dosage_form": None,
        "strength": None,
        "pack_size": "1 device",
        "rating": 4.8,
        "reviews_count": 2100,
        "in_stock": True,
    },
    {
        "name": "CoQ10 100mg Capsules",
        "category": "vitamins",
        "health_concern": "heart",
        "price": 549.0,
        "original_price": 699.0,
        "stock": 90,
        "description": "Coenzyme Q10 supplement for heart health and cellular energy production.",
        "manufacturer": "Himalaya",
        "requires_prescription": False,
        "dosage_form": "capsule",
        "strength": "100mg",
        "pack_size": "30 capsules",
        "rating": 4.4,
        "reviews_count": 380,
        "in_stock": True,
    },

    # ── Immunity Boosters ──────────────────────────────────────────────────────
    {
        "name": "Vitamin C 1000mg Effervescent Tablets",
        "category": "vitamins",
        "health_concern": "immunity",
        "price": 199.0,
        "original_price": 249.0,
        "stock": 300,
        "description": "High-dose Vitamin C for immune support and antioxidant protection.",
        "manufacturer": "Limcee",
        "requires_prescription": False,
        "dosage_form": "effervescent tablet",
        "strength": "1000mg",
        "pack_size": "20 tablets",
        "rating": 4.6,
        "reviews_count": 1850,
        "in_stock": True,
    },
    {
        "name": "Zinc + Vitamin D3 Combo Pack",
        "category": "vitamins",
        "health_concern": "immunity",
        "price": 349.0,
        "original_price": 449.0,
        "stock": 200,
        "description": "Essential minerals and vitamins for immune system support.",
        "manufacturer": "Zincovit",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "Zinc 10mg + D3 1000IU",
        "pack_size": "60 tablets",
        "rating": 4.5,
        "reviews_count": 920,
        "in_stock": True,
    },
    {
        "name": "Chyawanprash Special",
        "category": "ayurveda",
        "health_concern": "immunity",
        "price": 249.0,
        "original_price": 299.0,
        "stock": 160,
        "description": "Traditional Ayurvedic immunity booster with 40+ herbs.",
        "manufacturer": "Dabur",
        "requires_prescription": False,
        "dosage_form": "paste",
        "strength": None,
        "pack_size": "500g",
        "rating": 4.7,
        "reviews_count": 3200,
        "in_stock": True,
    },
    {
        "name": "Multivitamin Daily Complete",
        "category": "vitamins",
        "health_concern": "immunity",
        "price": 449.0,
        "original_price": 599.0,
        "stock": 250,
        "description": "Complete daily multivitamin with 23 essential nutrients.",
        "manufacturer": "Revital H",
        "requires_prescription": False,
        "dosage_form": "capsule",
        "strength": None,
        "pack_size": "30 capsules",
        "rating": 4.4,
        "reviews_count": 2750,
        "in_stock": True,
    },

    # ── Bone & Joint ───────────────────────────────────────────────────────────
    {
        "name": "Calcium + Vitamin D3 Tablets",
        "category": "vitamins",
        "health_concern": "bone",
        "price": 299.0,
        "original_price": 399.0,
        "stock": 220,
        "description": "Calcium carbonate with Vitamin D3 for strong bones and teeth.",
        "manufacturer": "Shelcal",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "Ca 500mg + D3 250IU",
        "pack_size": "60 tablets",
        "rating": 4.5,
        "reviews_count": 1640,
        "in_stock": True,
    },
    {
        "name": "Glucosamine & Chondroitin Capsules",
        "category": "vitamins",
        "health_concern": "bone",
        "price": 599.0,
        "original_price": 799.0,
        "stock": 100,
        "description": "Joint support supplement for cartilage health and mobility.",
        "manufacturer": "Himalaya",
        "requires_prescription": False,
        "dosage_form": "capsule",
        "strength": "Glucosamine 500mg + Chondroitin 400mg",
        "pack_size": "60 capsules",
        "rating": 4.3,
        "reviews_count": 780,
        "in_stock": True,
    },
    {
        "name": "Volini Pain Relief Gel",
        "category": "medicines",
        "health_concern": "bone",
        "price": 149.0,
        "original_price": 185.0,
        "stock": 300,
        "description": "Fast-acting topical gel for muscle and joint pain relief.",
        "manufacturer": "Pfizer",
        "requires_prescription": False,
        "dosage_form": "gel",
        "strength": "Diclofenac 1%",
        "pack_size": "50g",
        "rating": 4.6,
        "reviews_count": 4100,
        "in_stock": True,
    },
    {
        "name": "Knee Support Brace",
        "category": "medical_devices",
        "health_concern": "bone",
        "price": 499.0,
        "original_price": 699.0,
        "stock": 60,
        "description": "Adjustable knee support for arthritis, sports injuries and post-surgery recovery.",
        "manufacturer": "Tynor",
        "requires_prescription": False,
        "dosage_form": None,
        "strength": None,
        "pack_size": "1 piece (M/L/XL)",
        "rating": 4.4,
        "reviews_count": 1200,
        "in_stock": True,
    },

    # ── Mental Wellness ────────────────────────────────────────────────────────
    {
        "name": "Ashwagandha KSM-66 Extract",
        "category": "ayurveda",
        "health_concern": "mental",
        "price": 499.0,
        "original_price": 649.0,
        "stock": 140,
        "description": "Clinically studied adaptogen for stress relief and mental clarity.",
        "manufacturer": "Himalaya",
        "requires_prescription": False,
        "dosage_form": "capsule",
        "strength": "600mg",
        "pack_size": "60 capsules",
        "rating": 4.6,
        "reviews_count": 2300,
        "in_stock": True,
    },
    {
        "name": "Melatonin 5mg Sleep Aid",
        "category": "vitamins",
        "health_concern": "mental",
        "price": 349.0,
        "original_price": 449.0,
        "stock": 110,
        "description": "Natural sleep hormone supplement for better sleep quality.",
        "manufacturer": "NOW Foods",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "5mg",
        "pack_size": "60 tablets",
        "rating": 4.4,
        "reviews_count": 1560,
        "in_stock": True,
    },
    {
        "name": "Brahmi Memory Booster",
        "category": "ayurveda",
        "health_concern": "mental",
        "price": 199.0,
        "original_price": 249.0,
        "stock": 180,
        "description": "Ayurvedic herb for memory, concentration and cognitive function.",
        "manufacturer": "Patanjali",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "250mg",
        "pack_size": "60 tablets",
        "rating": 4.2,
        "reviews_count": 890,
        "in_stock": True,
    },
    {
        "name": "Magnesium Glycinate 400mg",
        "category": "vitamins",
        "health_concern": "mental",
        "price": 449.0,
        "original_price": 549.0,
        "stock": 90,
        "description": "Highly bioavailable magnesium for stress, anxiety and sleep support.",
        "manufacturer": "Doctor's Best",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "400mg",
        "pack_size": "120 tablets",
        "rating": 4.7,
        "reviews_count": 1100,
        "in_stock": True,
    },

    # ── Eye Care ───────────────────────────────────────────────────────────────
    {
        "name": "Refresh Tears Eye Drops",
        "category": "medicines",
        "health_concern": "eye",
        "price": 149.0,
        "original_price": 185.0,
        "stock": 250,
        "description": "Lubricating eye drops for dry eye relief and screen fatigue.",
        "manufacturer": "Allergan",
        "requires_prescription": False,
        "dosage_form": "eye drops",
        "strength": "0.5% CMC",
        "pack_size": "10ml",
        "rating": 4.7,
        "reviews_count": 3400,
        "in_stock": True,
    },
    {
        "name": "Lutein & Zeaxanthin Eye Supplement",
        "category": "vitamins",
        "health_concern": "eye",
        "price": 549.0,
        "original_price": 699.0,
        "stock": 80,
        "description": "Antioxidant supplement for macular health and blue light protection.",
        "manufacturer": "Ocuvite",
        "requires_prescription": False,
        "dosage_form": "softgel",
        "strength": "Lutein 20mg + Zeaxanthin 4mg",
        "pack_size": "60 softgels",
        "rating": 4.5,
        "reviews_count": 620,
        "in_stock": True,
    },
    {
        "name": "Anti-Glare Computer Glasses",
        "category": "medical_devices",
        "health_concern": "eye",
        "price": 799.0,
        "original_price": 1199.0,
        "stock": 45,
        "description": "Blue light blocking glasses for screen use and eye strain reduction.",
        "manufacturer": "Lenskart",
        "requires_prescription": False,
        "dosage_form": None,
        "strength": None,
        "pack_size": "1 pair",
        "rating": 4.3,
        "reviews_count": 1800,
        "in_stock": True,
    },

    # ── General Medicines ──────────────────────────────────────────────────────
    {
        "name": "Paracetamol 500mg Tablets",
        "category": "medicines",
        "health_concern": None,
        "price": 25.0,
        "original_price": 35.0,
        "stock": 500,
        "description": "Fever and mild-to-moderate pain relief.",
        "manufacturer": "Calpol",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "500mg",
        "pack_size": "15 tablets",
        "rating": 4.8,
        "reviews_count": 8900,
        "in_stock": True,
    },
    {
        "name": "Cetirizine 10mg Antihistamine",
        "category": "medicines",
        "health_concern": None,
        "price": 35.0,
        "original_price": 45.0,
        "stock": 400,
        "description": "Non-drowsy antihistamine for allergies, hay fever and hives.",
        "manufacturer": "Cipla",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "10mg",
        "pack_size": "10 tablets",
        "rating": 4.6,
        "reviews_count": 5200,
        "in_stock": True,
    },
    {
        "name": "Omeprazole 20mg Capsules",
        "category": "medicines",
        "health_concern": None,
        "price": 55.0,
        "original_price": 75.0,
        "stock": 300,
        "description": "Proton pump inhibitor for acidity, GERD and stomach ulcers.",
        "manufacturer": "Dr. Reddy's",
        "requires_prescription": False,
        "dosage_form": "capsule",
        "strength": "20mg",
        "pack_size": "14 capsules",
        "rating": 4.5,
        "reviews_count": 3100,
        "in_stock": True,
    },
    {
        "name": "ORS Electrolyte Sachets",
        "category": "medicines",
        "health_concern": None,
        "price": 45.0,
        "original_price": 60.0,
        "stock": 600,
        "description": "Oral rehydration salts for dehydration from diarrhoea or vomiting.",
        "manufacturer": "Electral",
        "requires_prescription": False,
        "dosage_form": "powder sachet",
        "strength": None,
        "pack_size": "10 sachets",
        "rating": 4.7,
        "reviews_count": 2800,
        "in_stock": True,
    },

    # ── Vitamins & Supplements ─────────────────────────────────────────────────
    {
        "name": "Vitamin B12 1000mcg Tablets",
        "category": "vitamins",
        "health_concern": None,
        "price": 299.0,
        "original_price": 399.0,
        "stock": 200,
        "description": "Methylcobalamin B12 for nerve health, energy and red blood cell formation.",
        "manufacturer": "Neurobion",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "1000mcg",
        "pack_size": "30 tablets",
        "rating": 4.6,
        "reviews_count": 2100,
        "in_stock": True,
    },
    {
        "name": "Iron + Folic Acid Tablets",
        "category": "vitamins",
        "health_concern": None,
        "price": 149.0,
        "original_price": 199.0,
        "stock": 250,
        "description": "Iron supplement with folic acid for anaemia prevention.",
        "manufacturer": "Feronia",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "Iron 60mg + Folic Acid 500mcg",
        "pack_size": "30 tablets",
        "rating": 4.4,
        "reviews_count": 1400,
        "in_stock": True,
    },
    {
        "name": "Whey Protein Isolate Chocolate",
        "category": "diet_nutrition",
        "health_concern": None,
        "price": 2499.0,
        "original_price": 3299.0,
        "stock": 70,
        "description": "High-quality whey protein isolate for muscle recovery and growth.",
        "manufacturer": "MuscleBlaze",
        "requires_prescription": False,
        "dosage_form": "powder",
        "strength": "25g protein per serving",
        "pack_size": "1kg",
        "rating": 4.5,
        "reviews_count": 4500,
        "in_stock": True,
    },

    # ── Personal Care ──────────────────────────────────────────────────────────
    {
        "name": "Neem Face Wash",
        "category": "personal_care",
        "health_concern": None,
        "price": 99.0,
        "original_price": 130.0,
        "stock": 350,
        "description": "Antibacterial neem face wash for acne-prone and oily skin.",
        "manufacturer": "Himalaya",
        "requires_prescription": False,
        "dosage_form": "liquid",
        "strength": None,
        "pack_size": "150ml",
        "rating": 4.4,
        "reviews_count": 6700,
        "in_stock": True,
    },
    {
        "name": "Sunscreen SPF 50+ PA+++",
        "category": "personal_care",
        "health_concern": None,
        "price": 349.0,
        "original_price": 449.0,
        "stock": 200,
        "description": "Broad-spectrum UVA/UVB protection for daily use.",
        "manufacturer": "Lotus Herbals",
        "requires_prescription": False,
        "dosage_form": "cream",
        "strength": "SPF 50+",
        "pack_size": "50g",
        "rating": 4.5,
        "reviews_count": 3800,
        "in_stock": True,
    },

    # ── Baby Care ──────────────────────────────────────────────────────────────
    {
        "name": "Baby Massage Oil",
        "category": "baby_care",
        "health_concern": None,
        "price": 149.0,
        "original_price": 199.0,
        "stock": 180,
        "description": "Gentle baby massage oil with almond and olive oil for soft skin.",
        "manufacturer": "Johnson's",
        "requires_prescription": False,
        "dosage_form": "oil",
        "strength": None,
        "pack_size": "200ml",
        "rating": 4.7,
        "reviews_count": 5100,
        "in_stock": True,
    },
    {
        "name": "Infant Paracetamol Drops",
        "category": "medicines",
        "health_concern": None,
        "price": 55.0,
        "original_price": 70.0,
        "stock": 200,
        "description": "Paracetamol oral drops for fever and pain in infants.",
        "manufacturer": "Calpol",
        "requires_prescription": False,
        "dosage_form": "oral drops",
        "strength": "100mg/ml",
        "pack_size": "15ml",
        "rating": 4.8,
        "reviews_count": 2900,
        "in_stock": True,
    },

    # ── Ayurveda ───────────────────────────────────────────────────────────────
    {
        "name": "Triphala Churna",
        "category": "ayurveda",
        "health_concern": None,
        "price": 99.0,
        "original_price": 130.0,
        "stock": 220,
        "description": "Classic Ayurvedic digestive tonic for gut health and detox.",
        "manufacturer": "Patanjali",
        "requires_prescription": False,
        "dosage_form": "powder",
        "strength": None,
        "pack_size": "200g",
        "rating": 4.5,
        "reviews_count": 3600,
        "in_stock": True,
    },
    {
        "name": "Giloy Tablets",
        "category": "ayurveda",
        "health_concern": "immunity",
        "price": 149.0,
        "original_price": 199.0,
        "stock": 190,
        "description": "Guduchi (Giloy) tablets for immunity, fever and anti-inflammatory support.",
        "manufacturer": "Himalaya",
        "requires_prescription": False,
        "dosage_form": "tablet",
        "strength": "250mg",
        "pack_size": "60 tablets",
        "rating": 4.4,
        "reviews_count": 1700,
        "in_stock": True,
    },

    # ── Fitness & Wellness ─────────────────────────────────────────────────────
    {
        "name": "Digital Thermometer",
        "category": "medical_devices",
        "health_concern": None,
        "price": 199.0,
        "original_price": 299.0,
        "stock": 300,
        "description": "Fast-read digital thermometer with fever alert and memory recall.",
        "manufacturer": "Dr. Morepen",
        "requires_prescription": False,
        "dosage_form": None,
        "strength": None,
        "pack_size": "1 device",
        "rating": 4.6,
        "reviews_count": 7200,
        "in_stock": True,
    },
    {
        "name": "Pulse Oximeter",
        "category": "medical_devices",
        "health_concern": "heart",
        "price": 799.0,
        "original_price": 1199.0,
        "stock": 80,
        "description": "Fingertip pulse oximeter for SpO2 and pulse rate monitoring.",
        "manufacturer": "Dr. Morepen",
        "requires_prescription": False,
        "dosage_form": None,
        "strength": None,
        "pack_size": "1 device",
        "rating": 4.7,
        "reviews_count": 4800,
        "in_stock": True,
    },
    {
        "name": "Resistance Bands Set",
        "category": "fitness",
        "health_concern": None,
        "price": 499.0,
        "original_price": 699.0,
        "stock": 120,
        "description": "Set of 5 resistance bands for home workouts and physiotherapy.",
        "manufacturer": "Boldfit",
        "requires_prescription": False,
        "dosage_form": None,
        "strength": None,
        "pack_size": "5 bands",
        "rating": 4.4,
        "reviews_count": 2200,
        "in_stock": True,
    },
]


async def seed():
    uri = os.getenv("MONGODB_URI")
    db_name = os.getenv("DB_NAME", "medai")

    if not uri:
        print("[ERROR] MONGODB_URI not set in environment. Check backend/.env")
        sys.exit(1)

    client = AsyncIOMotorClient(uri, server_api=ServerApi("1"))
    db = client[db_name]

    # Check existing count
    existing = await db.products.count_documents({})
    if existing > 0:
        print(f"[INFO] {existing} products already exist. Dropping and re-seeding...")
        await db.products.drop()

    now = datetime.utcnow()
    docs = []
    for p in PRODUCTS:
        doc = {**p, "created_at": now, "updated_at": now}
        docs.append(doc)

    result = await db.products.insert_many(docs)
    print(f"[OK] Inserted {len(result.inserted_ids)} products into '{db_name}.products'")

    # Create indexes for fast queries
    await db.products.create_index("category")
    await db.products.create_index("health_concern")
    await db.products.create_index([("name", "text"), ("description", "text")])
    print("[OK] Indexes created on category, health_concern, and text search")

    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
